### ISSUE TITLE
All requests are gone after the update

### ISSUE THREAD

**Issue by krzysztof-cywinski** [laika-labs/laika#11]
Hi guys,
first of all kudos for building Laika.
When it works it's a really great tool.

That being said, I've recently lost my entire workspace after an update on your hosted service.
Is there any way I can get it back or is it gone for good?
It worked this morning and in the afternoon it was gone.
How can I back up my workspace locally so that this doesnt' happen again (it's not the first time)?

**Comment by nonkung51** [comment]
Hi there @krzysztof-cywinski 
Thank you for the information, You can check https://legacy.getlaika.app for legacy version first if it's still existed or not.

Sorry for the inconvenience.

**Comment by nonkung51** [comment]
The previous version store the information in LocalStorage, but we still haven't implemented the migration to the new website.

@0xNithi will try to find the best way to cope with it.

**Comment by krzysztof-cywinski** [comment]
Thanks. This saved me quite some time recreating all of those requests. 
Is there a way to self-host the legacy version?
I like it better than the new one. 😅

**Comment by nonkung51** [comment]
The migration feature is completed :)

You can find it on collection pane, From that you can choose to export a legacy version (which stuck on local storage) and re-import it again.
<img width="393" alt="image" src="https://github.com/laika-labs/laika/assets/27486521/66696b01-3fd4-4ca3-afe9-dd582a8472f9">
<img width="634" alt="image" src="https://github.com/laika-labs/laika/assets/27486521/7ab1abcb-9b39-426b-b3b6-4bb204835929">

For legacy version we don't have self-host version because of there's some legal issues about it 😓
But you can also listed features that you want, and we would love to help you updated it :)

**Comment by krzysztof-cywinski** [comment]
Thanks for adding migrations, but I'll still stick with the legacy version for now.

The features I miss the most in the new version are:
1. the unit/number/hash tool in the right side toolbar. extremely useful tool that should hopefully be quite easy to port to the new version.
2. I can't find the environment settings anywhere and this has been one of the most important features
3. input structs are no longer decomposed into fields. there's a etherscan style tuple text field instead. it's more error prone, and overall a far worse UX, because now I need to tab back and forth between the definition and the input.
4. the UI no longer retains last call inputs and their results. this has been very convenient for me in the past.
